component/SEO.js, pages/[slug].js, pages/api/preview.js, pages/index.js
initial commit adding CORS origin setting and page meta tags
=> Proper SEO settings set

component/sections/contact/index.js, component/sections/contact/variant_a.js, component/sections/contact/variant_b.js
Fixes on how the section is shown on preview
=> update contact section code

component/SEO.js, pages/[slug].js, pages/index.js
Updated SEO metatags and pages to dynamically import the SEO component.
=> No social media seo image preview

component/sections/portfolio/index.js, component/sections/portfolio/variant_a.js, component/sections/portfolio/variant_b.js, component/sections/portfolio/variant_c.js, component/sections/portfolio/variant_d.js
Update frontend code to pick up changes from [portfolio schema fields](https://github.com/webriq-pagebuilder/sanity-packages/pull/10) and fix layout.
=> Fix portfolio section issues

component/sections/cookies/index.js, component/sections/cookies/variant_a.js, component/sections/cookies/variant_b.js, component/sections/cookies/variant_c.js, component/sections/cookies/variant_d.js, component/sections/cookies/variant_e.js, component/sections/cookies/variant_f.js, utils/cookies.js
Initial code changes for cookie implementation
=> Update code for cookies section to get implemented

component/sections/faqs/variant_a.js, component/sections/faqs/variant_b.js
FAQs update needed to add missing pagination in variant a and fix toggle view for variant b.
=> Fix FAQs section issues

component/sections/call_to_action/index.js, component/sections/call_to_action/variant_d.js, component/sections/pricing/index.js, component/sections/pricing/variant_d.js, component/sections/sign_in_sign_up/index.js, component/sections/sign_in_sign_up/variant_a.js, component/sections/sign_in_sign_up/variant_b.js, pages/api/query.js
Reference issue: [WebriQ forms sign in links not set](https://github.com/webriq-pagebuilder/studio-template-default/issues/33)
Sections: call to action (variant d), pricing (variant d) and sign up (variants a & b)
This update goes with this [sanity-packages pull request](https://github.com/webriq-pagebuilder/sanity-packages/pull/18).
=> update form static sign in link

component/sections/hero/variant_c.js, package.json, tailwind.config.js, yarn.lock
The header variant_c iframe container as not responsive to screen size.
Fixed: https://www.loom.com/share/caa4d3bdae44412683a4966fc0249926
=> Make iframe responsive

component/sections/pricing/index.js, component/sections/pricing/variant_a.js, component/sections/pricing/variant_b.js, component/sections/pricing/variant_c.js, pages/[slug].js
- Pricing was changed to Generic API Endpoints on requesting data
- Checkout button fix
=> pricing implementation changed to generic-api-endpoints

component/sections/portfolio/variant_a.js, component/sections/portfolio/variant_b.js, component/sections/portfolio/variant_c.js, component/sections/portfolio/variant_d.js
Update portfolio section Variant D that the "View more portfolios" button displays all portfolios added retaining container styles for every 6 portfolios.
=> Working view more functionality for Variant D and other fixes

package.json, yarn.lock
Recently created WebriQ Studio reported issue on images failing to load on site preview. Screenshot showing issue:
Reference netlify issue suggesting fix:
https://answers.netlify.com/t/nextjs-images-502-responses/52043/11
=> Add latest ipx package to fix deployed site preview images not loading

package.json, yarn.lock
=> hotfix: remove ipx package

component/sections/hero/variant_b.js, component/sections/how_it_works/variant_a.js, component/sections/how_it_works/variant_b.js, component/sections/how_it_works/variant_c.js, component/sections/how_it_works/variant_d.js, component/sections/how_it_works/variant_e.js, component/sections/portfolio/index.js, component/sections/portfolio/variant_b.js, component/sections/portfolio/variant_c.js, pages/api/query.js
- fixes for initial values in preview
=> fixes for initialValues

component/sections/call_to_action/variant_d.js, component/sections/hero/variant_e.js, component/sections/sign_in_sign_up/variant_a.js, component/sections/sign_in_sign_up/variant_b.js
Kindly see reference issue - [Sign up section](https://crmplus.zoho.com/webriqgoesmad/index.do/cxapp/projects/webriqusa#buginfo/1512955000002969047/1512955000004658136)
Affected sections:
=> Issue-A0A6-I10 show more form fields on preview

component/sections/features/variant_a.js, component/sections/features/variant_b.js, component/sections/features/variant_d.js
=> Features section fixes

component/blog/index.js, component/sections/contact/variant_a.js, component/sections/cookies/variant_a.js, component/sections/cookies/variant_b.js, component/sections/cookies/variant_c.js, component/sections/cookies/variant_d.js, component/sections/cookies/variant_e.js, component/sections/pricing/variant_d.js, component/sections/text_component/variant_a.js, component/sections/text_component/variant_b.js, component/sections/text_component/variant_c.js
Reference doc: [Migrating from @sanity/block-content-to-react to @portabletext/react](https://github.com/portabletext/react-portabletext/blob/main/MIGRATING.md)
=> migrate block content to portable text

component/ecwid/AddToWishlist.js, component/ecwid/ProductDetail.js, component/ecwid/Ribbon.js, component/sections/featured_products/variant_a.js, component/sections/navigation/variant_e.js, component/sections/pages_featuredProducts/index.js, component/sections/pages_featuredProducts/variant_a.js, component/sections/pages_featuredProducts/variant_b.js, component/sections/pages_productInfo/index.js, component/sections/pages_productInfo/variant_a.js, component/sections/pages_productInfo/variant_b.js, component/sections/product_info/index.js, component/sections/product_info/variant_a.js, component/sections/wishlist/index.js, component/sections/wishlist/variant_a.js, context/EcwidContext.js, pages/_app.js, pages/api/ecwid/products/[id].js, pages/api/query.js, pages/cart/index.js, pages/collections/[slug].js, pages/products/[slug].js, styles/globals.css, utils/useScript.js
- load ecwid script separately on _app.js and not from ecwidContext 
- Add ecwidContext to specific template pages like wishlist, products, cart and collections and those components that uses ecwid elements
- Fix cart icon not loading on pages
- Fix pages that uses ecwid components to display data and fix add to cart and add to wishlist (ex. /commerce-demo) 
- Fix collection not showing ribbon label
=> fixes and update on components and templates data

yarn.lock
=> Upgrade package versions for site

pages/api/submitForm/index.js
Upon form submission, it only returns successful payment (stripe - OK) but the form was not submitted successfully.
=> Fix form submission error on Pricing Variant D

.gitignore, netlify.toml, next-sitemap.config.js, package.json, yarn.lock
Link to package: https://www.npmjs.com/package/next-sitemap
External updates: Make sure to disable Netlify sitemap plugin for staging from Netlify deploy
TO DO: Implement this same PR to `master` branch
=> Update sitemap implementation using next-sitemap

context/EcwidContext.tsx
Zoho task: [Fix product page not loading](https://crmplus.zoho.com/webriqgoesmad/index.do/cxapp/projects/webriqusa#taskdetail/1512955000002969047/1512955000009739017/1512955000009942204)
Reference PR: [Ticket #15479 Page not loading #18](https://github.com/webriq/dxp-site-extrememotus-img3/pull/18)
=> Fix product page not loading

package.json, yarn.lock
=> Resolve import module on site preview

package.json, yarn.lock
This updates the Netlify Next.js plugin to latest @netlify/plugin-nextjs@4.41.3
=> Hotfixes Netlify Issue

package.json, yarn.lock
Update Netlify next.js plugin to latest.
=> Fix 500 error

components/ecwid/ProductDetail.tsx
Zoho task: [C-Studio | Product page option percent price modifier not working](https://crmplus.zoho.com/webriqgoesmad/index.do/cxapp/projects/webriqusa#taskdetail/1512955000002969047/1512955000010155745/1512955000011298364)
=> Fix product page price modifier not working

.github/workflows/chromatic.yml
This improves Storybook workflow by adding capability to cache node_modules
=> Improve Storybook workflow by adding cache

pages/studio/[[...index]].tsx
Issue: `Error: Unauthorized Session not found` randomly shows up when running auto login for StackShift UI
Zoho issue: [A0A6-I73: Error: Unauthorized - Session not found](https://crmplus.zoho.com/webriqgoesmad/index.do/cxapp/projects/webriqusa#buginfo/1512955000002969047/1512955000012766035)
=> Refactor Autologin

components/ThemeSettings.tsx
=> Hotfix: Theme Settings not loaded

plopfile.mjs
=> fix: logo cloud, how it works, signin signup component
